In [1]:
import pandas as pd
df = pd.read_csv ('TB_Burden_Country.csv')
print (df.shape)

(5120, 47)

In [2]:
df.head()

,Country or territory name,ISO 2-character country/territory code,ISO 3-character country/territory code,ISO numeric country/territory code,Region,Year,Estimated total population number,Estimated prevalence of TB (all forms) per 100 000 population,"Estimated prevalence of TB (all forms) per 100 000 population, low bound","Estimated prevalence of TB (all forms) per 100 000 population, high bound",...,Estimated incidence of TB cases who are HIV-positive per 100 000 population,"Estimated incidence of TB cases who are HIV-positive per 100 000 population, low bound","Estimated incidence of TB cases who are HIV-positive per 100 000 population, high bound",Estimated incidence of TB cases who are HIV-positive,"Estimated incidence of TB cases who are HIV-positive, low bound","Estimated incidence of TB cases who are HIV-positive, high bound",Method to derive TBHIV estimates,"Case detection rate (all forms), percent","Case detection rate (all forms), percent, low bound","Case detection rate (all forms), percent, high bound"
0,Afghanistan,AF,AFG,4,EMR,1990,11731193,306.0,156.0,506.0,...,0.11,0.08,0.14,12.0,9.4,16.0,NaN,20.0,15.0,24.0
1,Afghanistan,AF,AFG,4,EMR,1991,12612043,343.0,178.0,562.0,...,0.13,0.11,0.16,17.0,14.0,20.0,NaN,96.0,80.0,110.0
2,Afghanistan,AF,AFG,4,EMR,1992,13811876,371.0,189.0,614.0,...,0.16,0.14,0.18,22.0,19.0,24.0,NaN,NaN,NaN,NaN
3,Afghanistan,AF,AFG,4,EMR,1993,15175325,392.0,194.0,657.0,...,0.19,0.17,0.21,28.0,25.0,31.0,NaN,NaN,NaN,NaN
4,Afghanistan,AF,AFG,4,EMR,1994,16485018,410.0,198.0,697.0,...,0.21,0.18,0.24,35.0,30.0,39.0,NaN,NaN,NaN,NaN

In [3]:
#dropping columns that are  empty 
#checking which ones are empty columns
empty_cols = df.columns[df.isnull().all()].tolist()
print("Fully empty columns:",empty_cols)

df = df.drop(columns = empty_cols)

Fully empty columns: ['Method to derive TBHIV estimates']

In [4]:
print(df.shape)

(5120, 46)

In [5]:
#dropping other columns i might not need for analysis

cols_to_drop = [
    'ISO 2-character country/territory code',
    'Method to derive prevalence estimates',
    'Method to derive mortality estimates',
    'Method to derive incidence estimates',
    'Estimated prevalence of TB (all forms) per 100 000 population, low bound',
    'Estimated prevalence of TB (all forms) per 100 000 population, high bound',
    'Estimated prevalence of TB (all forms), low bound',
    'Estimated prevalence of TB (all forms), high bound',
    'Case detection rate (all forms), percent, low bound',
    'Case detection rate (all forms), percent, high bound',
]

df = df.drop(columns = [c for c in cols_to_drop if c in df.columns])
print(df.shape)
df.columns.tolist()

(5120, 36)

['Country or territory name',
 'ISO 3-character country/territory code',
 'ISO numeric country/territory code',
 'Region',
 'Year',
 'Estimated total population number',
 'Estimated prevalence of TB (all forms) per 100 000 population',
 'Estimated prevalence of TB (all forms)',
 'Estimated mortality of TB cases (all forms, excluding HIV) per 100 000 population',
 'Estimated mortality of TB cases (all forms, excluding HIV), per 100 000 population, low bound',
 'Estimated mortality of TB cases (all forms, excluding HIV), per 100 000 population, high bound',
 'Estimated number of deaths from TB (all forms, excluding HIV)',
 'Estimated number of deaths from TB (all forms, excluding HIV), low bound',
 'Estimated number of deaths from TB (all forms, excluding HIV), high bound',
 'Estimated mortality of TB cases who are HIV-positive, per 100 000 population',
 'Estimated mortality of TB cases who are HIV-positive, per 100 000 population, low bound',
 'Estimated mortality of TB cases who are HIV-positive, per 100 000 population, high bound',
 'Estimated number of deaths from TB in people who are HIV-positive',
 'Estimated number of deaths from TB in people who are HIV-positive, low bound',
 'Estimated number of deaths from TB in people who are HIV-positive, high bound',
 'Estimated incidence (all forms) per 100 000 population',
 'Estimated incidence (all forms) per 100 000 population, low bound',
 'Estimated incidence (all forms) per 100 000 population, high bound',
 'Estimated number of incident cases (all forms)',
 'Estimated number of incident cases (all forms), low bound',
 'Estimated number of incident cases (all forms), high bound',
 'Estimated HIV in incident TB (percent)',
 'Estimated HIV in incident TB (percent), low bound',
 'Estimated HIV in incident TB (percent), high bound',
 'Estimated incidence of TB cases who are HIV-positive per 100 000 population',
 'Estimated incidence of TB cases who are HIV-positive per 100 000 population, low bound',
 'Estimated incidence of TB cases who are HIV-positive per 100 000 population, high bound',
 'Estimated incidence of TB cases who are HIV-positive',
 'Estimated incidence of TB cases who are HIV-positive, low bound',
 'Estimated incidence of TB cases who are HIV-positive, high bound',
 'Case detection rate (all forms), percent']

In [6]:
#using regular expression in the naming of columnsand for pattern naming
import re

def to_snake_case(col):
    col = col.strip()
    col = col.replace('/', ' ').replace(',', '')
    col = re.sub(r'[^\w\s]', '', col)   # strip remaining punctuation
    col = re.sub(r'\s+', '_', col)       # spaces -> underscores
    return col.lower()

df.columns = [to_snake_case(c) for c in df.columns]
df.columns.tolist()

['country_or_territory_name',
 'iso_3character_country_territory_code',
 'iso_numeric_country_territory_code',
 'region',
 'year',
 'estimated_total_population_number',
 'estimated_prevalence_of_tb_all_forms_per_100_000_population',
 'estimated_prevalence_of_tb_all_forms',
 'estimated_mortality_of_tb_cases_all_forms_excluding_hiv_per_100_000_population',
 'estimated_mortality_of_tb_cases_all_forms_excluding_hiv_per_100_000_population_low_bound',
 'estimated_mortality_of_tb_cases_all_forms_excluding_hiv_per_100_000_population_high_bound',
 'estimated_number_of_deaths_from_tb_all_forms_excluding_hiv',
 'estimated_number_of_deaths_from_tb_all_forms_excluding_hiv_low_bound',
 'estimated_number_of_deaths_from_tb_all_forms_excluding_hiv_high_bound',
 'estimated_mortality_of_tb_cases_who_are_hivpositive_per_100_000_population',
 'estimated_mortality_of_tb_cases_who_are_hivpositive_per_100_000_population_low_bound',
 'estimated_mortality_of_tb_cases_who_are_hivpositive_per_100_000_population_high_bound',
 'estimated_number_of_deaths_from_tb_in_people_who_are_hivpositive',
 'estimated_number_of_deaths_from_tb_in_people_who_are_hivpositive_low_bound',
 'estimated_number_of_deaths_from_tb_in_people_who_are_hivpositive_high_bound',
 'estimated_incidence_all_forms_per_100_000_population',
 'estimated_incidence_all_forms_per_100_000_population_low_bound',
 'estimated_incidence_all_forms_per_100_000_population_high_bound',
 'estimated_number_of_incident_cases_all_forms',
 'estimated_number_of_incident_cases_all_forms_low_bound',
 'estimated_number_of_incident_cases_all_forms_high_bound',
 'estimated_hiv_in_incident_tb_percent',
 'estimated_hiv_in_incident_tb_percent_low_bound',
 'estimated_hiv_in_incident_tb_percent_high_bound',
 'estimated_incidence_of_tb_cases_who_are_hivpositive_per_100_000_population',
 'estimated_incidence_of_tb_cases_who_are_hivpositive_per_100_000_population_low_bound',
 'estimated_incidence_of_tb_cases_who_are_hivpositive_per_100_000_population_high_bound',
 'estimated_incidence_of_tb_cases_who_are_hivpositive',
 'estimated_incidence_of_tb_cases_who_are_hivpositive_low_bound',
 'estimated_incidence_of_tb_cases_who_are_hivpositive_high_bound',
 'case_detection_rate_all_forms_percent']

In [7]:
#forgot to drop this column of ISO
df = df.drop(columns = ['iso_numeric_country_territory_code'])
df.shape

(5120, 35)

In [8]:
#renaming the column names to short-form

df = df.rename(columns={
    'country_or_territory_name': 'country',
    'iso_3character_country_territory_code': 'iso3',

    'estimated_total_population_number': 'population',

    'estimated_prevalence_of_tb_all_forms_per_100_000_population': 'prevalence_rate',
    'estimated_prevalence_of_tb_all_forms': 'prevalence_cases',

    'estimated_mortality_of_tb_cases_all_forms_excluding_hiv_per_100_000_population': 'mortality_rate',
    'estimated_mortality_of_tb_cases_all_forms_excluding_hiv_per_100_000_population_low_bound': 'mortality_rate_low',
    'estimated_mortality_of_tb_cases_all_forms_excluding_hiv_per_100_000_population_high_bound': 'mortality_rate_high',

    'estimated_number_of_deaths_from_tb_all_forms_excluding_hiv': 'deaths',
    'estimated_number_of_deaths_from_tb_all_forms_excluding_hiv_low_bound': 'deaths_low',
    'estimated_number_of_deaths_from_tb_all_forms_excluding_hiv_high_bound': 'deaths_high',

    'estimated_mortality_of_tb_cases_who_are_hivpositive_per_100_000_population': 'mortality_rate_hiv',
    'estimated_mortality_of_tb_cases_who_are_hivpositive_per_100_000_population_low_bound': 'mortality_rate_hiv_low',
    'estimated_mortality_of_tb_cases_who_are_hivpositive_per_100_000_population_high_bound': 'mortality_rate_hiv_high',

    'estimated_number_of_deaths_from_tb_in_people_who_are_hivpositive': 'deaths_hiv',
    'estimated_number_of_deaths_from_tb_in_people_who_are_hivpositive_low_bound': 'deaths_hiv_low',
    'estimated_number_of_deaths_from_tb_in_people_who_are_hivpositive_high_bound': 'deaths_hiv_high',

    'estimated_incidence_all_forms_per_100_000_population': 'incidence_rate',
    'estimated_incidence_all_forms_per_100_000_population_low_bound': 'incidence_rate_low',
    'estimated_incidence_all_forms_per_100_000_population_high_bound': 'incidence_rate_high',

    'estimated_number_of_incident_cases_all_forms': 'incident_cases',
    'estimated_number_of_incident_cases_all_forms_low_bound': 'incident_cases_low',
    'estimated_number_of_incident_cases_all_forms_high_bound': 'incident_cases_high',

    'estimated_hiv_in_incident_tb_percent': 'hiv_in_incident_tb_pct',
    'estimated_hiv_in_incident_tb_percent_low_bound': 'hiv_in_incident_tb_pct_low',
    'estimated_hiv_in_incident_tb_percent_high_bound': 'hiv_in_incident_tb_pct_high',

    'estimated_incidence_of_tb_cases_who_are_hivpositive_per_100_000_population': 'incidence_rate_hiv',
    'estimated_incidence_of_tb_cases_who_are_hivpositive_per_100_000_population_low_bound': 'incidence_rate_hiv_low',
    'estimated_incidence_of_tb_cases_who_are_hivpositive_per_100_000_population_high_bound': 'incidence_rate_hiv_high',

    'estimated_incidence_of_tb_cases_who_are_hivpositive': 'incident_cases_hiv',
    'estimated_incidence_of_tb_cases_who_are_hivpositive_low_bound': 'incident_cases_hiv_low',
    'estimated_incidence_of_tb_cases_who_are_hivpositive_high_bound': 'incident_cases_hiv_high',

    'case_detection_rate_all_forms_percent': 'case_detection_rate',
})

print(df.shape)
df.columns.tolist()

(5120, 35)

['country',
 'iso3',
 'region',
 'year',
 'population',
 'prevalence_rate',
 'prevalence_cases',
 'mortality_rate',
 'mortality_rate_low',
 'mortality_rate_high',
 'deaths',
 'deaths_low',
 'deaths_high',
 'mortality_rate_hiv',
 'mortality_rate_hiv_low',
 'mortality_rate_hiv_high',
 'deaths_hiv',
 'deaths_hiv_low',
 'deaths_hiv_high',
 'incidence_rate',
 'incidence_rate_low',
 'incidence_rate_high',
 'incident_cases',
 'incident_cases_low',
 'incident_cases_high',
 'hiv_in_incident_tb_pct',
 'hiv_in_incident_tb_pct_low',
 'hiv_in_incident_tb_pct_high',
 'incidence_rate_hiv',
 'incidence_rate_hiv_low',
 'incidence_rate_hiv_high',
 'incident_cases_hiv',
 'incident_cases_hiv_low',
 'incident_cases_hiv_high',
 'case_detection_rate']

In [9]:
#checking data types
df.dtypes

country                         object
iso3                            object
region                          object
year                             int64
population                       int64
prevalence_rate                float64
prevalence_cases               float64
mortality_rate                 float64
mortality_rate_low             float64
mortality_rate_high            float64
deaths                         float64
deaths_low                     float64
deaths_high                    float64
mortality_rate_hiv             float64
mortality_rate_hiv_low         float64
mortality_rate_hiv_high        float64
deaths_hiv                     float64
deaths_hiv_low                 float64
deaths_hiv_high                float64
incidence_rate                 float64
incidence_rate_low             float64
incidence_rate_high            float64
incident_cases                 float64
incident_cases_low             float64
incident_cases_high            float64
hiv_in_incident_tb_pct         float64
hiv_in_incident_tb_pct_low     float64
hiv_in_incident_tb_pct_high    float64
incidence_rate_hiv             float64
incidence_rate_hiv_low         float64
incidence_rate_hiv_high        float64
incident_cases_hiv             float64
incident_cases_hiv_low         float64
incident_cases_hiv_high        float64
case_detection_rate            float64
dtype: object

In [10]:
#checking for duplicates if any
#exact full-row duplicates
print("Exact duplicate rows:",df.duplicated().sum())

#also checking duplicate country and year pairs - they should be unique with one row per country per year
print("Duplicated country year pairs:", df.duplicated(subset =['country','year']).sum())

Exact duplicate rows: 0
Duplicated country year pairs: 0

In [11]:
#checking null patterns in HIV-related olumns to conifm the assumption of the early 2,000 ish
hiv_cols = [ c for c in df.columns if 'hiv' in c]
print(hiv_cols)

#also checking th e null rate by year for each HIV column
df.groupby('year')[hiv_cols].apply(lambda x: x.isnull().mean())

['mortality_rate_hiv', 'mortality_rate_hiv_low', 'mortality_rate_hiv_high', 'deaths_hiv', 'deaths_hiv_low', 'deaths_hiv_high', 'hiv_in_incident_tb_pct', 'hiv_in_incident_tb_pct_low', 'hiv_in_incident_tb_pct_high', 'incidence_rate_hiv', 'incidence_rate_hiv_low', 'incidence_rate_hiv_high', 'incident_cases_hiv', 'incident_cases_hiv_low', 'incident_cases_hiv_high']

,mortality_rate_hiv,mortality_rate_hiv_low,mortality_rate_hiv_high,deaths_hiv,deaths_hiv_low,deaths_hiv_high,hiv_in_incident_tb_pct,hiv_in_incident_tb_pct_low,hiv_in_incident_tb_pct_high,incidence_rate_hiv,incidence_rate_hiv_low,incidence_rate_hiv_high,incident_cases_hiv,incident_cases_hiv_low,incident_cases_hiv_high
year,,,,,,,,,,,,,,,
1990,0.0,0.433962,0.433962,0.0,0.433962,0.433962,0.287736,0.297170,0.297170,0.287736,0.297170,0.297170,0.287736,0.297170,0.297170
1991,0.0,0.419811,0.419811,0.0,0.419811,0.419811,0.287736,0.292453,0.292453,0.287736,0.292453,0.292453,0.287736,0.292453,0.292453
1992,0.0,0.391509,0.391509,0.0,0.391509,0.391509,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736
1993,0.0,0.382075,0.382075,0.0,0.382075,0.382075,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736
1994,0.0,0.382075,0.382075,0.0,0.382075,0.382075,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736
1995,0.0,0.377358,0.377358,0.0,0.377358,0.377358,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736
1996,0.0,0.377358,0.377358,0.0,0.377358,0.377358,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736
1997,0.0,0.367925,0.367925,0.0,0.367925,0.367925,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736
1998,0.0,0.372642,0.372642,0.0,0.372642,0.372642,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736
1999,0.0,0.372642,0.372642,0.0,0.372642,0.372642,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736
2000,0.0,0.377358,0.377358,0.0,0.377358,0.377358,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736
2001,0.0,0.377358,0.377358,0.0,0.377358,0.377358,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736,0.287736
2002,0.0,0.375587,0.375587,0.0,0.375587,0.375587,0.291080,0.291080,0.291080,0.291080,0.291080,0.291080,0.291080,0.291080,0.291080
2003,0.0,0.375587,0.375587,0.0,0.375587,0.375587,0.291080,0.291080,0.291080,0.291080,0.291080,0.291080,0.291080,0.291080,0.291080
2004,0.0,0.380282,0.380282,0.0,0.380282,0.380282,0.291080,0.291080,0.291080,0.291080,0.291080,0.291080,0.291080,0.291080,0.291080
2005,0.0,0.383178,0.383178,0.0,0.383178,0.383178,0.285047,0.285047,0.285047,0.285047,0.285047,0.285047,0.285047,0.285047,0.285047
2006,0.0,0.383178,0.383178,0.0,0.383178,0.383178,0.285047,0.285047,0.285047,0.285047,0.285047,0.285047,0.285047,0.285047,0.285047
2007,0.0,0.373832,0.373832,0.0,0.373832,0.373832,0.285047,0.285047,0.285047,0.285047,0.285047,0.285047,0.285047,0.285047,0.285047
2008,0.0,0.364486,0.364486,0.0,0.364486,0.364486,0.285047,0.285047,0.285047,0.285047,0.285047,0.285047,0.285047,0.285047,0.285047
2009,0.0,0.359813,0.359813,0.0,0.359813,0.359813,0.285047,0.285047,0.285047,0.285047,0.285047,0.285047,0.285047,0.285047,0.285047
2010,0.0,0.370370,0.370370,0.0,0.370370,0.370370,0.291667,0.291667,0.291667,0.291667,0.291667,0.291667,0.291667,0.291667,0.291667
2011,0.0,0.368664,0.368664,0.0,0.368664,0.368664,0.290323,0.290323,0.290323,0.290323,0.290323,0.290323,0.290323,0.290323,0.290323
2012,0.0,0.368664,0.368664,0.0,0.368664,0.368664,0.290323,0.290323,0.290323,0.290323,0.290323,0.290323,0.290323,0.290323,0.290323
2013,0.0,0.368664,0.368664,0.0,0.368664,0.368664,0.290323,0.290323,0.290323,0.290323,0.290323,0.290323,0.290323,0.290323,0.290323

In [12]:
# Which countries have NO hiv_in_incident_tb_pct estimate at all, across all years?
countries_missing_hiv_pct = df.groupby('country')['hiv_in_incident_tb_pct'].apply(lambda x: x.isnull().all())
print("Countries missing this estimate in ALL years:", countries_missing_hiv_pct.sum())

# Which countries have it in SOME years but not others?
countries_partial = df.groupby('country')['hiv_in_incident_tb_pct'].apply(lambda x: x.isnull().any() and not x.isnull().all())
print("Countries with partial missingness:", countries_partial.sum())

Countries missing this estimate in ALL years: 65
Countries with partial missingness: 0

In [15]:
#creating a new column to flag the the rows or countries with and without the hiv estimates with true and false
df['has_hiv_estimate'] = df['hiv_in_incident_tb_pct'].notnull()
df

,country,iso3,region,year,population,prevalence_rate,prevalence_cases,mortality_rate,mortality_rate_low,mortality_rate_high,...,hiv_in_incident_tb_pct_low,hiv_in_incident_tb_pct_high,incidence_rate_hiv,incidence_rate_hiv_low,incidence_rate_hiv_high,incident_cases_hiv,incident_cases_hiv_low,incident_cases_hiv_high,case_detection_rate,has_hiv_estimate
0,Afghanistan,AFG,EMR,1990,11731193,306.0,36000.0,37.0,24.0,54.0,...,0.04,0.08,0.11,0.08,0.14,12.0,9.4,16.0,20.0,True
1,Afghanistan,AFG,EMR,1991,12612043,343.0,43000.0,46.0,29.0,61.0,...,0.06,0.09,0.13,0.11,0.16,17.0,14.0,20.0,96.0,True
2,Afghanistan,AFG,EMR,1992,13811876,371.0,51000.0,54.0,34.0,68.0,...,0.07,0.10,0.16,0.14,0.18,22.0,19.0,24.0,NaN,True
3,Afghanistan,AFG,EMR,1993,15175325,392.0,59000.0,60.0,38.0,73.0,...,0.09,0.11,0.19,0.17,0.21,28.0,25.0,31.0,NaN,True
4,Afghanistan,AFG,EMR,1994,16485018,410.0,68000.0,65.0,41.0,79.0,...,0.10,0.13,0.21,0.18,0.24,35.0,30.0,39.0,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5115,Zimbabwe,ZWE,AFR,2009,12888918,449.0,58000.0,39.0,27.0,52.0,...,65.00,85.00,511.00,460.00,566.00,66000.0,59000.0,73000.0,50.0,True
5116,Zimbabwe,ZWE,AFR,2010,13076978,415.0,54000.0,36.0,25.0,48.0,...,64.00,88.00,487.00,433.00,545.00,64000.0,57000.0,71000.0,53.0,True
5117,Zimbabwe,ZWE,AFR,2011,13358738,417.0,56000.0,38.0,26.0,51.0,...,63.00,85.00,448.00,403.00,502.00,60000.0,54000.0,67000.0,48.0,True
5118,Zimbabwe,ZWE,AFR,2012,13724317,425.0,58000.0,41.0,27.0,55.0,...,58.00,84.00,411.00,362.00,471.00,56000.0,50000.0,65000.0,45.0,True
5119,Zimbabwe,ZWE,AFR,2013,14149648,409.0,58000.0,40.0,25.0,52.0,...,55.00,86.00,395.00,341.00,464.00,56000.0,48000.0,66000.0,42.0,True

In [17]:
#lets flag the countries or years missing case detection rates as true or false
df['has_detection_estimate'] = df['case_detection_rate'].notnull()
df

,country,iso3,region,year,population,prevalence_rate,prevalence_cases,mortality_rate,mortality_rate_low,mortality_rate_high,...,hiv_in_incident_tb_pct_high,incidence_rate_hiv,incidence_rate_hiv_low,incidence_rate_hiv_high,incident_cases_hiv,incident_cases_hiv_low,incident_cases_hiv_high,case_detection_rate,has_hiv_estimate,has_detection_estimate
0,Afghanistan,AFG,EMR,1990,11731193,306.0,36000.0,37.0,24.0,54.0,...,0.08,0.11,0.08,0.14,12.0,9.4,16.0,20.0,True,True
1,Afghanistan,AFG,EMR,1991,12612043,343.0,43000.0,46.0,29.0,61.0,...,0.09,0.13,0.11,0.16,17.0,14.0,20.0,96.0,True,True
2,Afghanistan,AFG,EMR,1992,13811876,371.0,51000.0,54.0,34.0,68.0,...,0.10,0.16,0.14,0.18,22.0,19.0,24.0,NaN,True,False
3,Afghanistan,AFG,EMR,1993,15175325,392.0,59000.0,60.0,38.0,73.0,...,0.11,0.19,0.17,0.21,28.0,25.0,31.0,NaN,True,False
4,Afghanistan,AFG,EMR,1994,16485018,410.0,68000.0,65.0,41.0,79.0,...,0.13,0.21,0.18,0.24,35.0,30.0,39.0,NaN,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5115,Zimbabwe,ZWE,AFR,2009,12888918,449.0,58000.0,39.0,27.0,52.0,...,85.00,511.00,460.00,566.00,66000.0,59000.0,73000.0,50.0,True,True
5116,Zimbabwe,ZWE,AFR,2010,13076978,415.0,54000.0,36.0,25.0,48.0,...,88.00,487.00,433.00,545.00,64000.0,57000.0,71000.0,53.0,True,True
5117,Zimbabwe,ZWE,AFR,2011,13358738,417.0,56000.0,38.0,26.0,51.0,...,85.00,448.00,403.00,502.00,60000.0,54000.0,67000.0,48.0,True,True
5118,Zimbabwe,ZWE,AFR,2012,13724317,425.0,58000.0,41.0,27.0,55.0,...,84.00,411.00,362.00,471.00,56000.0,50000.0,65000.0,45.0,True,True
5119,Zimbabwe,ZWE,AFR,2013,14149648,409.0,58000.0,40.0,25.0,52.0,...,86.00,395.00,341.00,464.00,56000.0,48000.0,66000.0,42.0,True,True

In [19]:
df.to_csv('tb_data_clean.csv', index = False)

In [20]:
# In your Jupyter notebook
df.to_csv('tb_data_clean.csv', index=False)